services:
  mongodb:
    image: mongo:8
    container_name: clientflow-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - clientflow-mongodb-data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  clientflow-mongodb-data:
